"""add users table + timestamp and owner relationship for posts

Revision ID: 2ebf4f2521a0
Revises: 8800617a2fe5
Create Date: 2022-02-03 13:43:44.404596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebf4f2521a0'
down_revision = '8800617a2fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('posts', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('posts', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.alter_column('posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('posts', 'owner_id')
    op.drop_column('posts', 'created_at')
    op.drop_table('users')
    # ### end Alembic commands ###
