"""fix: add unique constraint for username + created_at columns for users and comments tables

Revision ID: c4c9fc093177
Revises: b3d76d6ad3f7
Create Date: 2022-02-11 13:36:07.393374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c9fc093177'
down_revision = 'b3d76d6ad3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("timezone('utc', now())"), nullable=True))
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
